[tool.robotcode]
python-path = ["./libraries"]

[tool.robotcode.robot]
paths = ["./tasks", "./tests"]

[tool.robotcode.lint]
enabled = true

[tool.robocop]
language = ["en", "fi"]

[tool.robocop.lint]
ignore = [
    "missing-doc-test-case",
    "missing-doc-keyword",
    "no-test-variable",
]
configure = [
    "line-too-long.line_length=110"
]

[tool.robocop.format]
select = ["NormalizeNewLines"]
configure = [
    "NormalizeNewLines.section_lines=2"
]
line_length = 110
