[tool.robotcode]
python-path = ["./libraries"]

[tool.robotcode.robot]
paths = ["./tasks", "./tests"]

[tool.robotcode.lint]
enabled = true

[tool.robocop]
language = ["en", "fi"]

[tool.robocop.lint]
select = [
    "rulename",
    "ruleid"
]
extend-select = [
    "additional-rule"
]
ignore = [
    "missing-doc-test-case",
    "missing-doc-keyword",
    "no-test-variable",
]
reports = ["all", "sarif"]
persistent = true
compare = true
configure = [
    "line-too-long.line_length=110"
]

[tool.robocop.format]
select = ["NormalizeNewLines"]
configure = [
    "NormalizeNewLines.section_lines=2"
]
diff = true
line_length = 110
skip = [
    "documentation"
]
reruns = 3
